site_name: Dispense matematica
site_url: https://sarakka.github.io/MathDocs/

theme:
  language: it
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Passa alla modalità scura

    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Passa alla modalità chiara


nav:
  - Home: index.md
  - Fondamenti di Algebra:
      - Monomi: algebra/monomi.md
      - Polinomi: algebra/polinomi.md
      - Espressioni: algebra/espressioni.md
  - Fondamenti di Geometria:
      - Piano cartesiano: geometria/intro.md
      - Pitagora: geometria/pitagora.md
      - Area e perimetro: geometria/poligoni.md
  - Equazioni 1° grado:
      - Principi: equazioni_1/principi.md
      - Metodo: equazioni_1/metodo.md
      - Esercizi: equazioni_1/esercizi.md


# per supportare LaTeX via MathJax
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

watch:
  - docs