site_name: Dispense matematica
site_url: https://sarakka.github.io/MathDocs/

theme:
  language: it
  name: material
  icon:
    annotation: material/plus-circle
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Passa alla modalità scura

    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Passa alla modalità chiara


nav:
  - Home: index.md
  - Fondamenti di Algebra:
      - Monomi: algebra/monomi.md
      - Polinomi: algebra/polinomi.md
      - Espressioni: algebra/espressioni.md
  - Equazioni 1° grado:
      - Principi: equazioni_1/principi.md
      - Metodo: equazioni_1/metodo.md
      - Esercizi: equazioni_1/esercizi.md
  - Equazioni 2° grado:
      - Definizione: equazioni_2/definizione.md
      - Pure: equazioni_2/pure.md
      - Spurie: equazioni_2/spurie.md
      - Complete: equazioni_2/complete.md
      - Esercizi: equazioni_2/esercizi.md
  - Disequazioni:
      - 2° grado: disequazioni/2_grado.md


# per supportare LaTeX via MathJax
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

watch:
  - docs